name: Build and Test
on: [push]
jobs:

  local_test_job:
    name: Running Local Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK
        with:
          distribution: 'zulu'
          java-version: '17'
        uses: actions/setup-java@v4
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Debug Tests
        run: ./gradlew testDebugUnitTest --continue
      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '**/build/reports/tests/'

  android_test_job:
    name: Android Tests
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        with:
        distribution: 'zulu'
        java-version: '17'
        uses: actions/setup-java@v4
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest

      - name: Upload Android Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: android-test-reports
          path: '**/build/reports/androidTests/'

  build_job:
            name: Building the APK
            runs-on: ubuntu-latest
            continue-on-error: true
            steps:
              - name: Checkout
                uses: actions/checkout@v4
              - name: Set up JDK
                with:
                  distribution: 'zulu'
                  java-version: '17'
                  uses: actions/setup-java@v4
              - name: Restore Cache
                uses: actions/cache@v4
                with:
                  path: |
                    ~/.gradle/caches
                    ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
                  restore-keys: |
                    ${{ runner.os }}-gradle-
              - name: Change wrapper permissions
                run: chmod +x ./gradlew
              - name: Assemble Debug
                run: ./gradlew assembleDebug

              - name: Upload APK
                uses: actions/upload-artifact@v2
                with:
                  name: apk
                  path: app/build/outputs/apk/debug/**.apk