name: Android CI
on:
  push:
    branches: [ master ]
    pull:
      branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: Checking out branch
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'OryLoginForm'
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2.0.10